apiVersion: apps/v1
kind: Deployment
metadata:
  name: return-users
  labels:
    app: return-users
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      name: take-home-test-node
  template:
    metadata:
      labels:
        app: take-home-test-node
    spec:
      containers:
      - name: return-users-container
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: return-users
  ports:
  - name: cont1-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080